name: CI

on:
  # pull_request_target:
  #   types: [opened, synchronize]
  #   branches: 
  #     - master
  #     # Temporarily allow check on dev/flutter2-iris branch
  #     - 'dev/flutter2-iris'
    
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.0'
      - run: flutter pub get
      - name: Run flutter build apk
        run: flutter build apk
        working-directory: example

  build_ios:
    name: Build iOS
    runs-on: macos-11
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.0'
      - run: flutter pub get
      - name: Run flutter build ios --no-codesign
        run: flutter build ios --no-codesign
        working-directory: example
